[package]
name = "reg-interface"
version = "0.1.0"
edition = "2021"
authors = ["Syfaro <syfaro@huefox.com>"]

[dependencies]
aamva = { git = "https://github.com/Syfaro/aamva-rs", version = "0.1.0" }
async-hid = "0.1.0"
async-trait = "0.1.81"
async-tungstenite = { version = "0.26.2", features = ["tokio-runtime", "tokio-rustls-webpki-roots"] }
eyre = "0.6.12"
futures = "0.3.30"
hex = "0.4.3"
ipp = { version = "5.0.3", default-features = false, features = [
    "async",
    "async-client",
] }
open = "5.3.0"
reqwest = { version = "0.12.5", default-features = false, features = ["rustls-tls", "json", "stream"] }
rhai = { version = "1.19.0", features = ["serde", "sync"] }
rumqttc = { version = "0.24.0", features = ["url"] }
serde = { version = "1.0.204", features = ["derive", "rc"] }
serde_json = "1.0.120"
tap = "1.0.1"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
tokio-serial = "5.4.4"
tokio-util = "0.7.11"
toml = "0.8.14"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.2"
