name: Artifacts

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/reg-interface"
